version: "3"

services:
  mariadb:
    container_name: "${DOCKER_CONTAINER_PREFIX}-mariadb"
    build:
      context: ./
      dockerfile: ./docker/mariadb/Dockerfile
    volumes:
      - ./docker/mariadb/data:/var/lib/mysql
    restart: "always"
    ports:
      - ${DB_PORT}:${DB_INTERNAL_PORT}
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=${DB_ALLOW_EMPTY_PASSWORD}

  phpmyadmin:
    container_name: "${DOCKER_CONTAINER_PREFIX}-phpmyadmin"
    build:
      context: ./
      dockerfile: ./docker/phpmyadmin/Dockerfile
    restart: "always"
    ports:
      - "${PMA_PORT}:80"
    links:
      - mariadb
    environment:
      - PMA_HOST=${DOCKER_CONTAINER_PREFIX}-mariadb
      - PMA_PORT=${DB_INTERNAL_PORT}
      - PMA_USER=${DB_USER}
      - PMA_PASSWORD=${DB_PASSWORD}
